image: debian/stable
packages:
  - cmake
  - catch2
  - qtbase5-dev
  - gcc
sources:
  - https://git.sr.ht/~cbondurant/Lipuma
  - https://github.com/Auburn/FastNoise2
tasks:
  - fastnoise: |
      cd FastNoise2
      cmake -S . -B build -D FASTNOISE2_NOISETOOL=OFF -D FASTNOISE2_TESTS=OFF
      cd build
      sudo make install
  - build: |
      cd Lipuma
      cmake -S . -B build
      cd build
      make
  - test: |
      cd Lipuma/build
      make test
